name: Deploy to Lightsail

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Lightsail
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: 22
          source: "*.html,css/*,js/*,fonts/*,img/*,pages/*,router/*,data/*,main.js"
          target: "/opt/bitnami/projects/myExpress/public/hiroko.design"
          overwrite: true
          debug: true

